baseURL = 'http://bigdata-adocs.github.io/'
languageCode = 'en-us'
title = 'Digital Twins for Accelerated Discovery of Climate and Sustainability'
#theme = "hugo-universal-theme"
theme = "fuji"
builddrafts = false
relativeURLs = true
canonifyURLs = true

contentdir = "content"
layoutdir = "layouts"
publishdir = "public"

author = "Michiaki Tatsubori"

## Hugo Built-in Features
disqusShortname = "https-shenoybr-github-io-hugo-goa-demo" # Comment out to disable Disqus.
googleAnalytics = "XYZ"
enableRobotsTXT = true

## Site Settings
[params]
	Subtitle = 'BigData 2022 workshop, December 16, Osaka, Japan'
	intro = "Startup Guru Extraordinaire"
	dateformat = "Jan 2, 2006"

## Site Meta Settings
[params.meta]
description = "Simple minimalist theme"
keywords = "minimalist,blog,goa,hugo,developer"

## Social Accounts
[params.social]
github = "<username>"
instagram = "<username>"
xing = "<username>"
linkedin = "<username>"
twitter = "<username>"
facebook = "<username>"
google = "<username>"
googlescholar = "<account_id>"
stackoverflow = "<username>"
lastfm = "<username>"
goodreads = "<username>"
gitlab = "<username>"
bitbucket = "<username>"
fivehundredpx = "<username>"
flickr = "<username>"
foursquare = "<username>"
hackernews = "<username>"
kickstarter = "<username>"
patreon = "<username>"
pintrest = "<username>"
steam = "<username>"
reddit = "<username>"
snapchat = "<username>"
youtube = "<channelid>"
keybase = "<username>"
twitch = "<username>"
soundcloud = "<username>"
tumblr = "<username>"
strava = "<username>"
skype = "<username>"
telegram = "<username>"
whatsapp = "<username>"
email = "you@example.com"
pgp = "<key_fingerprint>"

## Extras
[params.extra]
poweredby = true
highlightjs = true
socialmarkup = true
toc = true
displayrssicon = true

## Main Menu
[[menu.main]]
    name = "blog"
    weight = 100
    identifier = "blog"
    url = "/blog/"
[[menu.main]]
    name = "about"
    identifier = "about"
    weight = 200
    url = "/about/"
[[menu.main]]
    name = "coderag"
    identifier = "coderag"
    weight = 300
    url = "/coderag/"

[[menu.link]]
name = "IEEE BigData 2022"
url = "https://bigdataieee.org/BigData2022/"
weight = 2
